# Generated by Django 3.2.19 on 2023-05-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='city',
        ),
    ]
