# Generated by Django 3.2.19 on 2023-05-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hr.location'),
            preserve_default=False,
        ),
    ]
