# Generated by Django 3.2.19 on 2023-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20230602_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
