# Generated by Django 3.2.19 on 2023-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_employee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
