# Generated by Django 3.2.19 on 2023-06-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project',
        ),
    ]
