# Generated by Django 3.2.19 on 2023-06-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0002_auto_20230601_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='barbers',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='barber',
            field=models.ManyToManyField(to='barbershops.Barber'),
        ),
        migrations.DeleteModel(
            name='BarbershopBarbers',
        ),
    ]
